- components/footer.tsx
- components/header.tsx
- firebase.tsx
- pages/detail.tsx
- pages/index.tsx
firebase.tsx
import Storage, Auth 
header.tsx footer.tsx
기초 셋팅
by @ehfdl
> ⚡️ Feat(initial)

- .gitignore
- .prettierrc
- config/index.ts
- firebase.ts
- .prettierrc 초기 설정 파일 추가합니다.
- firebase configkey 환경변수 추가합니다.
feature/codeConvention -> dev
- 환경변수 및 프로젝트 공통 초기 설정 Setting 했습니다.
by @hwuiinn
> ⚡️  Feat : Setting

- pages/post/write.tsx
#3
게시물 작성 기능을 개발합니다.
feature/write-> dev
게시물 작성 기능을 개발합니다.
사진 추가기능을 개발합니다.
firebase 추가 기능을 개발합니다.
by @ehfdl
> ⚡️ Feat:Write #3

- components/navbar/cate_navbar.tsx
- components/navbar/ohju_navbar.tsx
- pages/mypage.tsx
#22 
mypage UI(와이어프레임)을 개발합니다.
feature/mypageUI -> dev
mypage UI(와이어프레임)을 개발합니다.
by @ehfdl
> Feature/mypage UI

- components/join_Modal.tsx
- components/layout.tsx
- components/login_Modal.tsx
- 회원가입 모달에서 일어나는 오류를 해결하고, Firebase Users Collection 시작 구조를 만듭니다.
feature/header -> dev
- 회원가입 모달에서 자꾸 .catch(err) 알림이 뜨는 오류를 해결합니다.
- 회원가입 시, 동일한 이메일이 있으면 알람을 띄웁니다. (커스텀 모달로 디벨롭 예정)
- 회원가입 후, 바로 로그인 모달로 전환됩니다.
(이하 Firebase 내용)
- Firebase 회원가입 시,  Users Collection API 시작 설정합니다.
- Users Collection 시작을 유저 이메일로 시작되게 합니다.
by @Huwiinn
> ⚡️ Feat : SignUp, Firebase #27

- components/join_Modal.tsx
- 이메일과 비밀번호 유효성 검사 기능 추가합니다.
feature/update -> dev
- 이메일과 비밀번호 유효성 검사 기능 추가합니다.
by @Hwuiinn
> ✨ Feat : Email, Password double check #27

- components/header.tsx
- components/join_Modal.tsx
- components/login_modal.tsx
- components/profile_modal.tsx
- index.d.ts
- package-lock.json
- pages/mypage.tsx
#38 
프로필수정기능을 추가합니다.
header 마이페이지 링크 이동합니다.
feature/profile -> dev
프로필수정기능을 추가합니다.
사진, 자기소개, 닉네임 수정 가능
header 마이페이지 링크 이동합니다.
by @ehfdl
> ⚡️ Feat:mypage #38

- components/follow_modal.tsx
- components/following_modal.tsx
- components/join_Modal.tsx
- components/profile_modal.tsx
- package.json
- pages/_document.tsx
- pages/mypage.tsx
- pages/post/write.tsx
- tailwind.config.js
#42 
follow_modal UI 개발합니다.
feature/follow -> dev
follow_modal UI 개발합니다.
by @ehfdl
> 💄 Design:follow #42

- pages/mypage.tsx
like 총 갯수 조회를 추가합니다.
카테고리 항목별 게시물 수를 조회합니다.
feature/mylike -> dev
like 총 갯수 조회를 추가합니다.
카테고리 항목별 게시물 수를 조회합니다.
by @ehfdl
> ⚡️ Feat:mypage #49

- components/write_btn.tsx
- index.d.ts
- pages/mypage.tsx
- pages/post/write.tsx
write API date 추가합니다.
feature/write-API -> dev
write API date 추가합니다.
by @ehfdl
> ⚡️ Feat: write

- components/layout.tsx
- pages/index.tsx
write button fix
feature/write-API -> dev
로그인 없이 write 클릭시 로그인모달 창 뜨게 수정합니다.
by @ehfdl
> 🐛 Fix : write

- pages/mypage.tsx
recently tap error 수정합니다.
feature/recently -> dev
recently tap error 수정합니다.
by @ehfdl
> 🐛 Fix:mypage #59

- components/layout.tsx
- components/login_modal.tsx
- pages/mypage.tsx
dev fix 수정합니다.
feature/devfix -> dev
dev fix 수정합니다.
by @ehfdl
> 🐛 Fix: layout

- pages/mypage.tsx
console 삭제합니다.
feature/console -> dev
console 삭제합니다.
by @ehfdl
> 🐛 Fix: mypage

- pages/post/[postId].tsx
- pages/post/edit/[postId].tsx
by @kimdongzzi
- 렌더링이 계속 되는 문제를 해결합니다.
feature/post-mutation -> dev
- 렌더링이 계속 되는 문제를 해결합니다.
by @이름
> 🐛 Fix : Detail useffect #66

- pages/post/[postId].tsx
- pages/post/write.tsx
최근게시물 최대 12개, 최신에 본글이 제일 앞으로 오게 개발합니다.
feature/recently-fix -> dev
최근게시물 최대 12개, 최신에 본글이 제일 앞으로 오게 개발합니다.
by @ehfdl
> ⚡️ Feat:mypage #59

- components/sub_page/membership_grade_information.tsx
- components/sub_page/my_post_card.tsx
- components/sub_page/user_post_card.tsx
- pages/mypage.tsx
#78 
grade modal 추가합니다.
mypage card design 수정합니다.
feature/grademodal -> dev
grade modal 추가합니다.
mypage card design 수정합니다.
by @ehfdl
> 💄 Design:mypage #78

- pages/users/[userId].tsx
userPosts error 수정합니다.
feature/devfix -> dev
userPosts error 수정합니다.
by @ehfdl
> 🐛 Fix : userpage

- components/main_page/Banner.jsx
- components/main_page/Category.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/top_btn.tsx
- components/write_btn.tsx
- pages/index.tsx
Modify post list feature 
feature/main_postlist -> dev
메인페이지 컴포넌트를 분리하고 캐러쉘 기능을 추가합니다.
by @HanuKim
> ✨ Feat: Modify post list feature 

- components/login_modal.tsx
- components/sub_page/follow_modal_card.tsx
- pages/mypage.tsx
- pages/users/[userId].tsx
userpage follow 기능 추가합니다.
feature/follower -> dev
userpage follow 기능 추가합니다.
by @ehfdl
> ⚡️Feat:userpage #42

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/login_modal.tsx
- components/main_page/post_list.tsx
- components/sub_page/follow_modal_card.tsx
- pages/mypage.tsx
- pages/post/[postId].tsx
- pages/users/[userId].tsx
- styles/globals.css
- yarn.lock
⚡️ Feat : 댓글 페이지네이션 #92 
feature/comment-pagination -> dev
- 댓글의 페이지네이션을 구현합니다.
- 댓글 컴포넌트를 분리합니다. 
by @kimdongzzi
> ⚡️ Feat : 댓글 페이지네이션 #92

- components/header.tsx
- components/sub_page/alarm.tsx
- components/sub_page/alarm_card.tsx
- components/sub_page/alarm_modal.tsx
- index.d.ts
- pages/post/[postId].tsx
Alarm 기능 추가합니다.
feature/alarm -> dev
Alarm 기능 추가합니다.
댓글 작성시 알람 기능 추가합니다.
알림 삭제기능, 모두 읽음, 읽은것 모두 삭제 기능 추가합니다.
by @ehfdl
> ⚡️ Feat:Alarm #94

- components/comment/comments.tsx
- pages/post/[postId].tsx
comments 수정합니다.
feature/commentsfix -> dev
comments 수정합니다.
by @ehfdl
> 🐛 Fix: Comments

- index.d.ts
- pages/post/write.tsx
write 재료 분할기능 추가합니다.
feature/write-fix -> dev
write 재료 분할기능 추가합니다.
재료 3개 초과시 더 추가하기 버튼클릭시 input 3개 추가
유효성 체크완료,
실행시 Form타입 재지정, firebase 데이터 초기화 필요.
by @ehfdl
> ⚡️ Feat:write #99

- .firebaserc
- .gitignore
- components/dropdown.tsx
- components/header.tsx
- components/join_modal.tsx
- components/login_modal.tsx
- components/search.tsx
- database.rules.json
- firebase.json
- firestore.indexes.json
- firestore.rules
- pages/_document.tsx
- pages/api/kakao.ts
- pages/index.tsx
- pages/search_page.tsx
- public/service-account.json
- styles/globals.css
- yarn.lock
ex) 로그인/회원가입 모달 UI 수정 및 카카오 로그인 구현, 로그아웃 버그 수정, 검색 기능 구현만 해놓은 코드
feature/search -> dev
- 카카오 로그인 기능 구현합니다.
- 검색 기능만 구현합니다.
- 로그인, 회원가입 디자인 수정합니다.
- 헤더 로그인/회원가입 버튼 로그아웃 버그 수정합니다.
by @Huwiinn
> ✨ Feat : Kakao Login, Search #27

- components/comment/comments.tsx
- components/header.tsx
- components/join_modal.tsx
- components/login_modal.tsx
- pages/index.tsx
- pages/users/[userId].tsx
console.log 삭제합니다.
sort 에러 수정합니다.
feature/sort-fix -> dev
console.log 삭제합니다.
sort 에러 수정합니다.
by @ehfdl
> 🔥Remove:console

- components/comment/comments.tsx
- components/main_page/post_list.tsx
- components/sub_page/alarm.tsx
- components/sub_page/alarm_card.tsx
- components/sub_page/alarm_modal.tsx
- index.d.ts
- package.json
- pages/post/[postId].tsx
- tailwind.config.js
#94 
alarm UI 변경합니다.
알림 갯수 추가합니다.
feature/alarmUI -> dev
alarm UI 변경합니다.
알림 갯수 추가합니다.
by @ehfdl
> ⚡️ Feat:alarm

- components/comment/comment_list.tsx
- components/comment/recomment_list.tsx
- components/header.tsx
- components/ohzu_page/report_comment_card.tsx
- components/ohzu_page/report_post_card.tsx
- components/ohzu_page/report_recomment_card.tsx
- index.d.ts
- pages/ohzu.tsx
- pages/post/[postId].tsx
- pages/post/write.tsx
신고기능추가합니다.
feature/report -> dev
신고기능추가합니다.
게시글, 댓글, 답글 신고기능 추가.
관리자 계정에 저장.
by @ehfdl
> ⚡️ Feat: 신고 #109

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomments.tsx
- components/main_page/post_list.tsx
- index.d.ts
- pages/post/[postId].tsx
- pages/post/edit/[id].tsx
- pages/post/write.tsx
- tailwind.config.js
- 수정 페이지
- 디테일 페이지
- tailwind 
- 게시글 삭제
- 댓글 작성
feature/fix detail -> dev
- 수정 페이지에서 기본 사진 수정을 구현합니다.
- 디테일 페이지의 재료를 태그형식으로 가져옵니다.
- tailwind 기본 베이스의 색상을 저장합니다.
- 게시글 삭제 시 답글을 함께 지우도록 합니다.
- 댓글 작성 시 textarea의 높이가 자동조절 되도록 합니다.
#111 
by @kimdongzzi
> 🐛 Fix : 게시글 수정페이지 유효성 추가 #111

- components/sub_page/alarm_modal.tsx
- components/sub_page/my_post_card.tsx
- components/sub_page/profile_modal.tsx
- components/sub_page/user_post_card.tsx
alarm UI 색 변경합니다.
like head 가려짐 수정합니다.
feature/alarmfix -> dev
alarm UI 색 변경합니다.
like head 가려짐 수정합니다.
by @ehfdl
> 💄 Design: UI

- components/grade.tsx
- components/header.tsx
- components/sub_page/alarm.tsx
- components/sub_page/membership_grade_information.tsx
- pages/post/write.tsx
write 유효성검사 수정합니다.
grade 수정합니다.
alarm 사이즈 수정합니다.
feature/repair -> dev
write 유효성검사 수정합니다.
grade 수정합니다.
alarm 사이즈 수정합니다.
by @ehfdl
> 🐛 Fix:write

- components/sub_page/alarm_card.tsx
읽음 UI 수정합니다.
feature/alarm-fix -> dev
읽음 UI 수정합니다.
by @ehfdl
> 💄 Design:alarm

- components/main_page/banner.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
Modify main UI 
feature/fix_main_UI -> dev
메인페이지 UI를 수정합니다.
by @HanuKim
> 🎨 Feat: Modify main UI #61

- components/main_page/banner.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
Edit main UI
feature/main_banner -> dev
메인페이지 게시물 리스트 제목 텍스트, 배너 swiper 코드 오류를 수정합니다.
by @HanuKim
> 🎨 Feat: Edit main UI #61

- components/dropdown.tsx
- components/main_page/post_list.tsx
- components/search_card.tsx
- pages/search/[searchWord].tsx
dropdown 필터 기능 추가합니다.
feature/search-drop -> dev
dropdown 필터 기능 추가합니다.
by @ehfdl
> ⚡️ Feat: searchpage

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomment_list.tsx
- components/comment/recomments.tsx
- components/delete_modal.tsx
- components/join_modal.tsx
- pages/post/[postId].tsx
- pages/post/edit/[id].tsx
- pages/post/write.tsx
Comment & Detail UI  #132 
feature/refactor-comment -> dev
- 댓글과 답글 수정 시 textarea가 늘어나도록 수정합니다.
- 댓글과 답글 수정 시 textarea value가 남아있도록 합니다.
- 삭제 모달의 아이콘을 변경합니다.
- 회원가입 시 기본 프로필사진이 등록되도록 합니다.
by @kimdongzzi
> 🐛 Fix : Comment & Detail UI #132

- components/join_modal.tsx
- components/login_modal.tsx
간편로그인 시 재가입 방지합니다.
feature/user-img -> dev
간편로그인 시 재 가입 방지합니다.
기본이미지 추가합니다.
by @ehfdl
> 🐛 Fix:Login,Join

- components/dropdown.tsx
- components/header.tsx
- components/join_modal.tsx
- components/login_modal.tsx
- 회원가입, 로그인 기능 및 디자인 수정
feature/join -> dev
- 회원가입과 로그인 모달 디자인을 수정합니다.
- 회원가입 유효성 검사를 수정합니다.
- 로그인 실패 시, 에러처리 합니다.
by @Huwiinn
> 🐛  Fix : login/ join design, feature

- components/dropdown.tsx
- package.json
- pages/search/[searchWord].tsx
- pages/search/include/[search_include].tsx
- pages/users/[userId].tsx
window error fix 합니다.
dropdown shadow 제거합니다.
vercel-deploy 추가합니다.
hotfix/window-> main
window error fix 합니다.
dropdown shadow 제거합니다.
vercel-deploy 추가합니다.
by @ehfdl
> 🐛 Fix:window

- pages/search/[searchWord].tsx
- pages/search/include/[search_include].tsx
- pages/users/[userId].tsx
window 로직 getServerSideProps 로 수정합니다.
hotfix/window -> main
window 로직 getServerSideProps 로 수정합니다.
by @ehfdl
> OHZU Version 1.1

- components/join_modal.tsx
- components/login_modal.tsx
join 시 회원이면 재가입 막습니다.
hotfix/kakao -> main
join 시 회원이면 재가입 막습니다.
by @ehfdl
> OHZU Version 1.2

- components/join_modal.tsx
- components/login_modal.tsx
vercel 주소 변경합니다.
hotfix/kakao -> main
vercel 주소 변경합니다.
by @ehfdl
> OHZU Version 1.3

- components/header.tsx
- components/join_modal.tsx
- components/login_modal.tsx
- components/sub_page/alarm.tsx
- firebase.ts
- pages/_app.tsx
- pages/mypage.tsx
새고고침시 로그인 유지추가합니다.
로그아웃시 메인으로 이동합니다.
hotfix/kakao -> main
새고고침시 로그인 유지추가합니다.
로그아웃시 메인으로 이동합니다.
by @ehfdl
> 🐛 Fix: login

- components/comment/comment_list.tsx
- components/comment/recomment_list.tsx
- components/header.tsx
- pages/post/[postId].tsx
- 신고 후 동작을 추가합니다.
hotfix/report -> main
- 신고 후 동작을 추가합니다.
by @kimdongzzi
> 🐛 Fix : 신고 후 동작

- components/delete_modal.tsx
- components/follow_modal.tsx
- components/header.tsx
- components/join_modal.tsx
- components/login_modal.tsx
- components/sub_page/alarm_modal.tsx
- components/sub_page/profile_modal.tsx
modal backdrop blur 처리합니다.
modal on 시 스크롤 막습니다.
로그아웃시 세션제거 처리합니다.
hotfix/modal -> main
modal backdrop blur 처리합니다.
modal on 시 스크롤 막습니다.
로그아웃시 세션제거 처리합니다.
by @ehfdl
> OHZU Version 1.4

- components/header.tsx
- components/layout.tsx
- pages/index.tsx
- pages/post/[postId].tsx
- pages/search/[searchWord].tsx
- pages/search/include/[search_include].tsx
- pages/users/[userId].tsx
로그인시 페이지 재렌더링 추가합니다.
비회원 접근불가한 페이지 로그아웃시 메인이동 추가합니다.
hotfix/loggedin -> main
로그인시 페이지 재렌더링 추가합니다.
비회원 접근불가한 페이지 로그아웃시 메인이동 추가합니다.
by @ehfdl
> OHZU Version 1.5

- components/login_modal.tsx
#152 
email 저장 기능 추가합니다.
pw 틀렸을 때 alert 처리합니다.
feature/save-id -> dev
email 저장 기능 추가합니다.
pw 틀렸을 때 alert 처리합니다.
by @ehfdl
> ⚡️ Feat: Login

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomments.tsx
- components/sub_page/alarm_card.tsx
- index.d.ts
#94 
답글 알람기능 추가합니다.
alarm api 수정합니다.
feature/alarm-plus -> dev
답글 알람기능 추가합니다.
alarm api 수정합니다.
by @ehfdl
> ⚡️ Feat: alarm

- components/join_modal.tsx
- components/login_modal.tsx
- pages/_app.tsx
- pages/_document.tsx
- pages/api/naver.ts
#27
- 비밀번호 재설정
feature/login -> dev
- 비밀번호를 재설정 기능을 추가합니다.
by @hwuiinn
> # Feat : Password Reset 

- components/grade.tsx
- components/navbar/cate_navbar.tsx
- components/navbar/ohju_navbar.tsx
- components/sub_page/my_post_card.tsx
- pages/mypage.tsx
#22 
mobile-UI 반응형 추가합니다.
grade 추가합니다.
feature/mypage-UImobile -> dev
mobile-UI 반응형 추가합니다.
grade 추가합니다.
by @ehfdl
> 💄 Design:mypage

- components/follow_modal.tsx
- components/grade.tsx
- components/navbar/ohju_navbar.tsx
- components/sub_page/follow_modal_card.tsx
- components/sub_page/my_post_card.tsx
- components/sub_page/profile_modal.tsx
- pages/mypage.tsx
#22 
mypage modal UI mobile 추가합니다.
feature/mypage-mobile-UI -> dev
mypage modal UI mobile 추가합니다.
by @ehfdl
> 💄 Design: mypage

- pages/post/edit/[id].tsx
- pages/post/write.tsx
#167 
writepage-UI mobile 추가합니다.
수정 페이지-UI mobile 추가합니다.
feature/mobile-write-UI -> dev
writepage-UI mobile 추가합니다.
수정 페이지-UI mobile 추가합니다.
by @ehfdl
> 💄 Design:write,update

- components/navbar/user_cate_navbar.tsx
- components/sub_page/user_dropdown.tsx
- components/sub_page/user_post_card.tsx
- pages/mypage.tsx
- pages/users/[userId].tsx
#169 
userpage UI mobile 반응형 구현 합니다.
feature/userpage-UI -> dev
userpage UI mobile 반응형 구현 합니다.
by @ehfdl
> 💄 Design: userpage #169

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomment_list.tsx
- components/comment/recomments.tsx
- components/delete_modal.tsx
- components/grade.tsx
- components/layout.tsx
- package-lock.json
- pages/_app.tsx
- pages/post/[postId].tsx
- yarn.lock
디테일 페이지의 반응형 UI를 구현합니다.
feature/detail-responsive -> dev
디테일 페이지의 반응형 UI를 구현합니다.
#174 
by @kimdongzzi
> 🎨 Design : Detail Page Responsive Web UI #174

- components/main_page/banner.tsx
- components/main_page/category.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/top_btn.tsx
- components/write_btn.tsx
Add mobile main page
feature/update -> dev
메인 페이지 모바일 반응형 UI를 추가합니다.
by @HanuKim
> ✨ Feat: Add mobile main page #162

- components/comment/comment_list.tsx
- components/comment/recomment_list.tsx
- components/find_password.tsx
- components/footer.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/modal/confirm_modal.tsx
- components/search_card.tsx
- components/sub_page/alarm_modal.tsx
- components/sub_page/follow_modal_card.tsx
- components/sub_page/user_post_card.tsx
- pages/mypage.tsx
- pages/post/[postId].tsx
- pages/users/[userId].tsx
- modal ui 수정합니다.
- footer size 수정합니다.
- card size, border 수정합니다.
feature/subpage-UI -> dev
- modal ui 수정합니다.
- footer size 수정합니다.
- card size, border 수정합니다.
by @ehfdl
> 🐛 Fix: modal

- components/main_page/banner.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/modal/follow_modal.tsx
- components/sub_page/follow_modal_card.tsx
- components/top_btn.tsx
- pages/mypage.tsx
main postlist 구조 변경합니다.
follow모달 구조 변경합니다.
mypage 프로필 구조 변경합니다.
feature/dev-fix -> dev
main postlist 구조 변경합니다.
follow모달 구조 변경합니다.
mypage 프로필 구조 변경합니다.
by @ehfdl
> 🐛 Fix: design

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomment_list.tsx
- components/comment/recomments.tsx
- components/find_password.tsx
- components/footer.tsx
- components/header.tsx
- components/main_page/banner.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/modal/join_modal.tsx
- components/modal/login_modal.tsx
- components/modal/profile_modal.tsx
- components/sub_page/membership_grade_information.tsx
- components/top_btn.tsx
- components/write_btn.tsx
- pages/_document.tsx
- pages/mypage.tsx
- pages/post/[postId].tsx
alert modal 적용합니다.
top,write btn 위치 수정합니다.
배너 글 적용합니다.
프로필 사진 수정합니다.
mypage 높이 수정합니다.
feature/fix-dev -> dev
alert modal 적용합니다.
top,write btn 위치 수정합니다.
배너 글 적용합니다.
프로필 사진 수정합니다.
mypage 높이 수정합니다.
by @ohzu
> 🐛 Fix : page

- pages/about.tsx
- pages/post/write.tsx
about 문자열 수정합니다.
write 의존배열 window 제거합니다.
hotfix/window-> main
about 문자열 수정합니다.
write 의존배열 window 제거합니다.
by @ehfdl
> 🐛 Fix: window,about

- components/find_password.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/modal/join_modal.tsx
- components/modal/report_modal.tsx
- components/ohzu_page/report_comment_card.tsx
- components/ohzu_page/report_recomment_card.tsx
- components/sub_page/alarm_modal.tsx
- components/write_btn.tsx
- pages/post/[postId].tsx
- pages/post/write.tsx
- pages/users/[userId].tsx
write page 등록시 벗어날 때 모달 사라지게 추가합니다.
kakao url 변경합니다.
게시물 기본이미지 주소 변경합니다.
알람모달 mt 제거합니다.
console.log 제거합니다.
hotfix/version1.71 -> main
write page 등록시 벗어날 때 모달 사라지게 추가합니다.
kakao url 변경합니다.
게시물 기본이미지 주소 변경합니다.
알람모달 mt 제거합니다.
console.log 제거합니다.
by @ohzu
> OHZU Version1.71

- components/main_page/post_card.tsx
- components/search_card.tsx
- pages/post/[postId].tsx
- pages/search/[searchWord].tsx
search 게시물 수 수정합니다.
post 이미지 화질 개선합니다.
feature/update -> dev
search 게시물 수 수정합니다.
post 이미지 화질 개선합니다.
by @ohzu
> OHZU Version1.72

- components/modal/join_modal.tsx
- components/modal/login_modal.tsx
카카오 로그인 URL 수정
hotfix/kakaoURL -> main
- 카카오 로그인 Axios url 변경합니다.
by @Huwiinn
> 🐛 Fix : Kakao Axios URL

- components/comment/recomments.tsx
- components/grade.tsx
- components/header.tsx
- components/loading/loading.tsx
- components/main_page/banner.tsx
- components/main_page/category.tsx
- components/modal/follow_modal.tsx
- components/modal/global_modal.tsx
- components/recoil/modal.tsx
- components/sub_page/follow_modal_card.tsx
- components/sub_page/membership_grade_information.tsx
- pages/mypage.tsx
- pages/post/[postId].tsx
- pages/post/edit/[id].tsx
- pages/post/write.tsx
- pages/users/[userId].tsx
-header 문구 width, height 삭제합니다.
- 메인 탭 default Check 추가합니다.
- 배너 처음 전체에 꽉차는 모습 수정합니다.
- 알람 답글오류 수정합니다.
- profile image 화질 수정합니다.
- write src 오류 수정합니다.
- grade 설명창 사이즈 수정합니다.
- 로딩 속도 개선합니다.
- mypage,userpage 이전 버전으로 초기화합니다.
- follow error 처리합니다.
hotfix/img -> main
-header 문구 width, height 삭제합니다.
- 메인 탭 default Check 추가합니다.
- 배너 처음 전체에 꽉차는 모습 수정합니다.
- 알람 답글오류 수정합니다.
- profile image 화질 수정합니다.
- write src 오류 수정합니다.
- grade 설명창 사이즈 수정합니다.
- 로딩 속도 개선합니다.
- mypage,userpage 이전 버전으로 초기화합니다.
- follow error 처리합니다.
- 
by @ohzu
> OHZU Version 1.75

- components/footer.tsx
- components/header.tsx
- components/landing/landing_page.tsx
- components/layout.tsx
- pages/index.tsx
- pages/main.tsx
- pages/post/[postId].tsx
- pages/post/write.tsx
#201 
완성된 랜딩페이지 적용합니다.
feature/landingPage -> dev
- 랜딩페이지를 index.ts에 적용합니다. ("/")
- 기존 index.ts에 있는 코드를 main.tsx에 적용합니다. ("/main")
- 브랜드 로고 클릭시, /main으로 이동합니다.
by @Huwiinn
> ✅ Update : Landing page

- components/landing/landing_page.tsx
- tailwind.config.js
랜딩페이지 레이아웃 깨짐 수정합니다.
feature/landingPage -> dev
- absolute 속성을 제거하여 균일한 레이아웃을 적용합니다.
by @Huwiinn
> 🐛 Fix : Landing page UI

- components/landing/landing_page.tsx
- components/main_page/banner.tsx
바로가기 오류 수정 및 메인 배너 버튼 삭제
feature/landingPage -> dev
- 바로가기 텍스트를 눌러야만 main 페이지로 이동하는 현상 수정합니다.
- main banner button 제거합니다.
by @Hwuiinn
> 🐛 Fix : Landing button, banner button

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomment_list.tsx
- components/comment/recomments.tsx
- components/header.tsx
- components/main_page/banner.tsx
- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- components/search_card.tsx
- components/sub_page/alarm_card.tsx
- components/sub_page/follow_modal_card.tsx
- components/sub_page/my_post_card.tsx
- components/sub_page/user_post_card.tsx
- components/top_btn.tsx
- components/write_btn.tsx
- hooks/query/post/useUpdatePost.ts
- pages/post/[...title].tsx
- pages/post/edit/[...title].tsx
- pages/search/[...searchWord].tsx
- pages/users/[...nickname].tsx
- tailwind.config.js
- 포스트 아이디와 유저아이디를 숨깁니다.
- banner pagination 수정합니다.
- iconDefault 색상 수정합니다.
feature/router-query -> dev
- 포스트 아이디와 유저아이디를 숨깁니다.
- banner pagination 수정합니다.
- iconDefault 색상 수정합니다.
by @kimdongzzi
> 🐛 Fix : URL 표기 변경 #218 

- components/comment/comment_list.tsx
- components/comment/comments.tsx
- components/comment/recomment_list.tsx
- components/comment/recomments.tsx
- components/search_card.tsx
- pages/post/[...title].tsx
- tailwind.config.js
- Detail Page UI 변경합니다
feature/detail UI -> dev
- Detail Page UI 변경합니다
by @kimdongzzi
> 🎨 Design : Detail Page UI 변경 #222

- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- package-lock.json
Modify Main UI
ui/postlist-> dev
메인페이지 UI 수정합니다.
by @HanuKim
> 🎨 Design: Modify Main UI

- components/main_page/post_card.tsx
- components/main_page/post_list.tsx
- package-lock.json
postcard gap 조정합니다.
Feature/post-UI -> dev
postcard gap 조정합니다.
by @HanuKim
> Feature/post UI

- pages/post/[...title].tsx
- pages/search/[...searchWord].tsx
- pages/search/include/[search_include].tsx
- icon 중복 삭제
hotfix/icon -> main
- icon 중복 삭제
by @kimdongzzi
> 🐛 Fix : icon 중복 삭제

- pages/post/edit/[...title].tsx
🐛 Fix : 수정 페이지 데이터 불러오기 변경
hotfix/editpage -> main
- url 마스킹으로 인한 데이터 불러오기 방법을 변경합니다.
by @kimdongzzi
> OHZU Version 1.81

- components/modal/follow_modal.tsx
- components/modal/join_modal.tsx
- components/modal/login_modal.tsx
- components/modal/profile_modal.tsx
🐛 Fix : fix modal
hotfix/modal -> main
- modal 수정합니다.
by @kimdongzzi
> OHZU Version 1.82

- components/footer.tsx
- components/modal/alert_modal.tsx
- components/modal/confirm_modal.tsx
- components/modal/delete_account_modal.tsx
- components/modal/follow_modal.tsx
- components/modal/global_modal.tsx
- components/modal/join_modal.tsx
- components/modal/login_modal.tsx
- components/modal/profile_modal.tsx
- components/modal/report_modal.tsx
- components/recoil/modal.tsx
- pages/404.tsx
- pages/about.tsx
- pages/mypage.tsx
- pages/post/edit/[...title].tsx
- pages/search/[...searchWord].tsx
- public/image/exclamation_circle.svg
- 회원탈퇴 기능 구현
Hotfix/delete account -> main
- 회원탈퇴 기능 구현
by @Huwiinn
> OHZU Version 1.83

- components/main_page/post_card.tsx
Modify post cards in main page
feature/main_fix -> dev
메인페이지 카드 반응형을 개선합니다.
by @HanuKim
> 🎨 Design: Modify post cards in main page

- README.md
- pages/mypage.tsx
- pages/post/[...title].tsx
- pages/users/[...nickname].tsx
- font size 조정
- README 작성
feature/UI-fix -> dev
- font size 조정
- README 작성
by @kimdongzzi @Huwiinn
> 🎨 Design : README 작성

- pages/search/[...searchWord].tsx
- pages/search/include/[search_include].tsx
검색 모바일 레이아웃 수정 및 태그 키워드 검색 기능 개선
hotfix/mobile-searchUI -> main
- 모바일 환경에서 검색 시, 웹 레이아웃이 함께 나오는 현상 수정합니다.
- 태그 검색 시, 불안정한 검색기능 개선합니다. (소주 태그 클릭 => 보드카, 맥주 등의 내용이 같이 검색되었던 것)
by @Huwiinn
> OHZU Version 1.91
